-- Snowflake schema setup for dbt models (Phase 7)
-- Placeholders rendered by scripts/setup_dbt_schemas.py:
--   {{DATABASE}}, {{SCHEMA_STAGING}}, {{SCHEMA_INTERMEDIATE}}, {{SCHEMA_MARTS}}, {{ROLE}}

USE ROLE {{ROLE}};
USE WAREHOUSE {{WAREHOUSE}};
USE DATABASE {{DATABASE}};

CREATE SCHEMA IF NOT EXISTS {{DATABASE}}.{{SCHEMA_STAGING}};
CREATE SCHEMA IF NOT EXISTS {{DATABASE}}.{{SCHEMA_INTERMEDIATE}};
CREATE SCHEMA IF NOT EXISTS {{DATABASE}}.{{SCHEMA_MARTS}};

GRANT USAGE ON SCHEMA {{SCHEMA_STAGING}} TO ROLE {{ROLE}};
GRANT USAGE ON SCHEMA {{SCHEMA_INTERMEDIATE}} TO ROLE {{ROLE}};
GRANT USAGE ON SCHEMA {{SCHEMA_MARTS}} TO ROLE {{ROLE}};

GRANT CREATE VIEW ON SCHEMA {{SCHEMA_STAGING}} TO ROLE {{ROLE}};
GRANT CREATE VIEW ON SCHEMA {{SCHEMA_INTERMEDIATE}} TO ROLE {{ROLE}};
GRANT CREATE TABLE ON SCHEMA {{SCHEMA_MARTS}} TO ROLE {{ROLE}};

GRANT SELECT ON ALL TABLES IN SCHEMA {{SCHEMA_STAGING}} TO ROLE {{ROLE}};
GRANT SELECT ON ALL TABLES IN SCHEMA {{SCHEMA_INTERMEDIATE}} TO ROLE {{ROLE}};
GRANT SELECT ON ALL TABLES IN SCHEMA {{SCHEMA_MARTS}} TO ROLE {{ROLE}};

GRANT SELECT ON FUTURE TABLES IN SCHEMA {{SCHEMA_STAGING}} TO ROLE {{ROLE}};
GRANT SELECT ON FUTURE TABLES IN SCHEMA {{SCHEMA_INTERMEDIATE}} TO ROLE {{ROLE}};
GRANT SELECT ON FUTURE TABLES IN SCHEMA {{SCHEMA_MARTS}} TO ROLE {{ROLE}};
